---
title: "Picochlorum Growth Rate Analysis"
date: "`r Sys.Date()`"
author: "David Mah"
output:
  html_document: default
  rmdformats::readthedown:
    highlight: kate
  rmarkdown::html_vignette: 
    css: 
    - !expr system.file("rmarkdown/templates/html_vignette/resources/vignette.css", package = "rmarkdown")
    - !expr system.file("includes/stylesheets/summarytools.css", package = "summarytools")
  prettydoc::html_pretty:
    theme: architect
    highlight: github  
---


```{r knitr_init, echo=FALSE, cache=FALSE, warning=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=TRUE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               tidy = FALSE,
               fig.height=8, 
               fig.width=8,
               results = 'asis')
opts_knit$set(width=75)
```

```{r, message=FALSE, warning=FALSE}
library("ggplot2")
library("dplyr")
library("plotrix" ) # needed for standard error
library("readxl") # Read excel file
library("readr") 
library("lubridate") 
library("tidyr") 
library("pspline")
library("npregfast")
library("ggpmisc")

# This is to clear the device list (dev.list()) 
graphics.off()
 
```

```{r, echo = FALSE, message = FALSE}

# Read the metadata
flaskdata <- read_csv("../data/metadata/flaskdata.csv")

# Add time elapsed since culture start
flaskdata <- flaskdata %>% 
  dplyr::mutate(julian_culture_st= make_datetime(flaskdata$`culture year`,flaskdata$`culture month`,flaskdata$`culture day`,flaskdata$`culture hour`,flaskdata$`culture min`)) %>% 
  dplyr::mutate(julian_sample_st= make_datetime(flaskdata$`sample year`,flaskdata$`sample month`,flaskdata$`sample day`,flaskdata$`sample hour`,flaskdata$`sample min`))%>% 
  dplyr::mutate(days_elapsed = julian_sample_st-julian_culture_st) %>% 
  dplyr::mutate(FA = paste(flask,attempt, sep = "")) %>%
  dplyr::mutate(light_on = format(make_datetime(hour = flaskdata$`light hour`, min = flaskdata$`light min`), format = "%H:%M:%S")) %>%
  dplyr::mutate(dark_on = format(make_datetime(hour = flaskdata$`dark hour`, min = flaskdata$`dark min`), format = "%H:%M:%S")) %>%
  dplyr::mutate(light_on_datetime_1 = format(make_datetime(flaskdata$`sample year`,flaskdata$`culture month`,flaskdata$`sample day`,flaskdata$`light hour`, flaskdata$`light min`))) %>%
  dplyr::mutate(dark_on_datetime_1 = format(make_datetime(flaskdata$`sample year`,flaskdata$`culture month`,flaskdata$`sample day`,flaskdata$`dark hour`, flaskdata$`dark min`))) %>%
  dplyr::mutate(light_on_datetime_2 = format(make_datetime(flaskdata$`sample year`,flaskdata$`culture month`,flaskdata$`sample day`+1,flaskdata$`light hour`, flaskdata$`light min`))) %>%
  dplyr::mutate(dark_on_datetime_2 = format(make_datetime(flaskdata$`sample year`,flaskdata$`culture month`,flaskdata$`sample day`+1,flaskdata$`dark hour`, flaskdata$`dark min`))) %>%
  dplyr::mutate(datetime_1_tube_change= make_datetime(flaskdata$`1 tube change year`,flaskdata$`1 tube change month`,flaskdata$`1 tube change day`,flaskdata$`1 tube change hour`,flaskdata$`1 tube change min`))  %>% 
  dplyr::mutate(datetime_2_tube_change= make_datetime(flaskdata$`2 tube change year`,flaskdata$`2 tube change month`,flaskdata$`2 tube change day`,flaskdata$`2 tube change hour`,flaskdata$`2 tube change min`))  %>% 
  dplyr::mutate(datetime_3_tube_change= make_datetime(flaskdata$`3 tube change year`,flaskdata$`3 tube change month`,flaskdata$`3 tube change day`,flaskdata$`3 tube change hour`,flaskdata$`3 tube change min`))  %>%
  dplyr::mutate(datetime_4_tube_change= make_datetime(flaskdata$`4 tube change year`,flaskdata$`4 tube change month`,flaskdata$`4 tube change day`,flaskdata$`4 tube change hour`,flaskdata$`4 tube change min`)) 

# Read the Temperature Data
myfiles = list.files(path="../data/metadata/GEEK temp sensor1615178083103_export", pattern="*.csv", full.names=TRUE)
data_all <- lapply(myfiles, read_csv)
tempdata <- do.call(rbind, data_all)

## Read the data

# Find all csv files 
myfiles = list.files(path="../data", pattern="*.csv", full.names=TRUE)

# Read all csv files
data_all <- lapply(myfiles, read_csv, skip =2)
data <- do.call(rbind, data_all)

# Split the tube names
data <- data %>%
  dplyr::mutate(flask =  substr(`Tube Name:`, 1,1), 
                attempt = substr(`Tube Name:`, 2,2),
                hour_index = substr(`Tube Name:`, 3,4),
                AorM = substr(`Tube Name:`, 5,5),
                repli = substr(`Tube Name:`, 6,6)
                ) %>%
  dplyr::mutate(FA = paste(flask,attempt, sep = ""),
                FAhi = paste(flask, attempt,hour_index, sep = ""))

## Compare both dataframes to get julian start time and light regime
julian_time <- data.frame()
light_regime <- data.frame()
for (row in 1:nrow(data)){
index <- match(data[row,"FA"],flaskdata$FA)
julian_time <- rbind(julian_time,as.numeric(flaskdata[index,"days_elapsed"])+as.numeric(data[row,"hour_index"])/24)
light_regime <- rbind(light_regime, flaskdata[index,"light regime"])
}
names(julian_time)[1] <- "julian_time"
data<- cbind(data, julian_time)
names(light_regime)[1] <- "light_regime"
data<- cbind(data, light_regime)

# Add time sampled 
data <- data %>%
  dplyr::mutate(julian_time_diff = as.difftime(data$julian_time, format = "%d", units = "days"))
sample_datetime <- data.frame()
for (row in 1:nrow(data)){
index <- match(data[row,"FA"],flaskdata$FA)
sample_datetime <- rbind(sample_datetime, flaskdata[index,"julian_culture_st"]+data.frame(data[row,"julian_time_diff"]))
}
names(sample_datetime)[1] <- "sample_datetime"
data<- cbind(data, sample_datetime)

# Extract just time from sample
data <- data %>%
  dplyr::mutate(sample_time = format(sample_datetime, format = "%H:%M:%S"))
# data$sample_time <- strptime(data$sample_time,format="%H:%M")

# Loop through data to add "Light" or "Dark" as a another variable in the last column 
lightORdark <- data.frame()
LorD<- ""
# Check if it is light or dark
for (row in 1:nrow(data)){
index <- match(data[row,"FA"],flaskdata$FA)
# A, B, E, F have dark cycles ending after midnight. The rest of the samples cycles should end before midnight. 
if(data[row,"flask"] == "A" | data[row,"flask"] == "B" |data[row,"flask"] == "E"|data[row,"flask"] == "F"){
  ifelse(data[row,"sample_time"] >= flaskdata[index,"dark_on"] & data[row,"sample_time"] <= flaskdata[index,"light_on"], LorD <- "dark", LorD <- "light")
  }
else {
  ifelse(data[row,"sample_time"] >= flaskdata[index,"light_on"] & data[row,"sample_time"] <= flaskdata[index,"dark_on"], LorD <- "light", LorD <- "dark")
  }
lightORdark <- rbind(lightORdark, data.frame(LorD))
}
names(lightORdark)[1] <- "lightORdark"
data<- cbind(data, lightORdark)



# Loop through data and compare sampling times with the tube change data to determine how long it has been sitting in the sampler for

time_since_tube_change <- data.frame()
time_tube_change <- ""

# data<- filter(data,flask == "E")

for (row in 1:nrow(data)) {
  index <- match(data[row,"FA"],flaskdata$FA)
  if(data[row,"AorM"] == "A"){
    if (is.na(flaskdata[index,"datetime_1_tube_change"]) == "TRUE"){time_tube_change <- 0}
    else if (as.numeric(data[row,"sample_datetime"]) < as.numeric(flaskdata[index,"datetime_1_tube_change"])){
      time_tube_change <- as.numeric(flaskdata[index,"datetime_1_tube_change"]) - as.numeric(data[row,"sample_datetime"])
    }
    else if (is.na(flaskdata[index,"datetime_2_tube_change"]) == "TRUE"){time_tube_change <- 0}
    else if (as.numeric(data[row,"sample_datetime"]) >= as.numeric(flaskdata[index,"datetime_1_tube_change"]) & as.numeric(data[row,"sample_datetime"]) < as.numeric(flaskdata[index,"datetime_2_tube_change"])){
      time_tube_change <- as.numeric(flaskdata[index,"datetime_2_tube_change"]) - as.numeric(data[row,"sample_datetime"])
    }
    else if (is.na(flaskdata[index,"datetime_3_tube_change"]) == "TRUE"){time_tube_change <- 0}
    else if (as.numeric(data[row,"sample_datetime"]) >= as.numeric(flaskdata[index,"datetime_2_tube_change"]) & as.numeric(data[row,"sample_datetime"]) < as.numeric(flaskdata[index,"datetime_3_tube_change"])){
      time_tube_change <- as.numeric(flaskdata[index,"datetime_3_tube_change"]) - as.numeric(data[row,"sample_datetime"])
    }
    else if (is.na(flaskdata[index,"datetime_4_tube_change"]) == "TRUE"){time_tube_change <- 0}
    else if (as.numeric(data[row,"sample_datetime"]) >= as.numeric(flaskdata[index,"datetime_2_tube_change"]) & as.numeric(data[row,"sample_datetime"]) < as.numeric(flaskdata[index,"datetime_3_tube_change"])){
      time_tube_change <- as.numeric(flaskdata[index,"datetime_4_tube_change"]) - as.numeric(data[row,"sample_datetime"])
    }
    else {
      time_tube_change <- 0
    }
  }
else {time_tube_change <- 0}
  
# divide by 3600 because POSIXct as.numeric is in seconds. So final is hours since tube change. 
time_since_tube_change <- rbind(time_since_tube_change, time_tube_change/3600)
}
names(time_since_tube_change)[1] <- "time_since_tube_change"
data<- cbind(data, time_since_tube_change)


# Add in temp and humidity data from Govee recording device
# Don't add temp into the data file. You can just put it in later. 
# colnames(tempdata) <- c("sample_datetime", "Temperature", "Humidity")
# data <- right_join(data,tempdata, by = "sample_datetime")

## An Explanation of variables: 
# Geom. Mean—The geometric mean. Can be a more applicable metric for a log-normal distribution. It is always less than or equal to the arithmetic mean.
# Robust Standard Deviation—68.26% of the events around the Median are used for this calculation, and an upper and lower range set.  The robust standard deviation is equal to (upper range + lower range) /2.  If the upper range is off scale, the robust standard deviation is equal to the lower range, and vice versa when the lower range is off scale and the robust standard deviation is the upper range.  The robust standard deviation is not as skewed by outlying values as the Standard Deviation.
# Robust CV—Equals 100 * 1/2( Intensity[at 84.13 percentile] – Intensity [at 15.87 percentile] ) / Median. The robust CV is not as skewed by outlying values as the CV.


# Extract the more useful data
d_ss <- data %>%
  select(`flask`,attempt, hour_index, FAhi, AorM, repli,light_regime,julian_time,sample_datetime, sample_time,lightORdark,time_since_tube_change,`Picochlorum Events/μL(V)`, `Picochlorum Median FSC-A`, `Picochlorum Median SSC-A`, `Picochlorum Median PC5.5-A`)

```


```{r}
# TEMPORARY GRAPHIC - This includes code for: 
# Log transformation of y axis 
# Addition of grey box for dark portion of light regime 

# to add: 
# Make axis ticks better and overall aesthetic... 

# Create function to get plot limits of a ggplot (for creation of grey box)
get_plot_limits <- function(plot) {
    gb = ggplot_build(plot)
    xmin = gb$layout$panel_params[[1]]$x.range[1]
    xmax = gb$layout$panel_params[[1]]$x.range[2]
    ymin = gb$layout$panel_params[[1]]$y.range[1]
    ymax = gb$layout$panel_params[[1]]$y.range[2]
    list(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax)
}


FLASK<- filter(d_ss,flask == "E")
events <- ggplot(FLASK, aes(x = sample_datetime, y = `Picochlorum Events/μL(V)`))+ 
    scale_y_continuous(trans = "log10", sec.axis = sec_axis(~./4, name = "Temperature"))
plot_limits<-get_plot_limits(events)
events <- events + annotate(geom = "rect", 
                            xmin=as_datetime(filter(flaskdata, flask =="E")$dark_on_datetime_1),
                            xmax=as_datetime(filter(flaskdata, flask =="E")$light_on_datetime_2), 
                            ymin=10^plot_limits[[3]], 
                            ymax=10^plot_limits[[4]], alpha= 0.5, fill = "black") +
  geom_point(aes(color = AorM)) +
  xlab("Sample Date Time") +
  ylab("Log(Events/μL)") + 
  ggtitle("All Flasks Picochlorum Events/μL")
  labs(col="Light \nCondition") +
  theme_bw()+ 
  theme(axis.text=element_text(size=12),
        axis.title=element_text(size=12,face="bold"),
        legend.title =element_text(size=12,face="bold"),
        legend.text = element_text(size=12),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
  #png(file.path("../report/img","Events_Facet_Wrap.png"), width = 800, height = 600)
  print(events)
  #dev.off()  

```


```{r}
## Plot for Events

# Facet wrap plot of all Flasks together
events <- ggplot(d_ss, aes(x = julian_time, y = log(`Picochlorum Events/μL(V)`)))+
  geom_smooth() +
  geom_point(aes(color = lightORdark)) +
  xlab("Time Since Start") +
  ylab("Log(Events/μL)") + 
  ggtitle("All Flasks Picochlorum Events/μL")
  labs(col="Light \nCondition") +
  theme_bw()+ 
  theme(axis.text=element_text(size=12),
        axis.title=element_text(size=12,face="bold"),
        legend.title =element_text(size=12,face="bold"),
        legend.text = element_text(size=12)) 
events <- events + facet_wrap(~flask)
  png(file.path("../report/img","Events_Facet_Wrap.png"), width = 800, height = 600)
  print(events)
  dev.off()  


# Plot for Events/μL
for (letter in unique(d_ss$flask)) {
  FLASK<- filter(d_ss,flask == letter)
events <- ggplot(FLASK, aes(x = FLASK$julian_time, y = FLASK$`Picochlorum Events/μL(V)`))+
    geom_point(aes(color = lightORdark)) +
    xlab("Time since start") +
    ylab("Median Events/μL") + 
    labs(col="Light \nCondition") +
    theme_bw() +
    ggtitle(paste("Flask", letter)) + 
    theme(plot.title = element_text(size = 28, face = "bold"),
          axis.text=element_text(size=20),
          axis.title=element_text(size=20,face="bold"),
          legend.title =element_text(size=20,face="bold"),
          legend.text = element_text(size=20)) 
    # Create and store plots in img folder
  dev.new()
    png(file.path("../report/img",paste("Events", letter, ".png", sep="_")), width = 800, height = 600)
  print(events)
  dev.off()  
}
  
# Plot for log(Events)/μL
for (letter in unique(d_ss$flask)) {
  FLASK<- filter(d_ss,flask == letter)
events <- ggplot(FLASK, aes(x = FLASK$julian_time, y = log(FLASK$`Picochlorum Events/μL(V)`)))+
    geom_point(aes(color = lightORdark)) +
    xlab("Time since start") +
    ylab("Log(Median Events)/μL") + 
    labs(col="Light \nCondition") +
    theme_bw() +
    ggtitle(paste("Flask", letter)) + 
    theme(plot.title = element_text(size = 28, face = "bold"),
          axis.text=element_text(size=20),
          axis.title=element_text(size=20,face="bold"),
          legend.title =element_text(size=20,face="bold"),
          legend.text = element_text(size=20)) 
    # Create and store plots in img folder
  dev.new()
    png(file.path("../report/img",paste("Events_log", letter, ".png", sep="_")), width = 800, height = 600)
  print(events)
  dev.off()  
}

# Plot for FSC
for (letter in unique(d_ss$flask)) {
  FLASK<- filter(d_ss,flask == letter)
  FSC <- ggplot(FLASK, aes(x = FLASK$julian_time, y = FLASK$`Picochlorum Median FSC-A`))+
    geom_point(aes(color = lightORdark)) +
    xlab("Time since start") +
    ylab("Median FSC") + 
    labs(col="Light \nCondition") +
    theme_bw() +
    ggtitle(paste("Flask", letter)) + 
    theme(plot.title = element_text(size = 28, face = "bold"),
          axis.text=element_text(size=20),
          axis.title=element_text(size=20,face="bold"),
          legend.title =element_text(size=20,face="bold"),
          legend.text = element_text(size=20)) 
    # Create and store plots in img folder
  dev.new()
    png(file.path("../report/img",paste("FSC", letter, ".png", sep="_")), width = 800, height = 600)
  print(FSC)
  dev.off()
}

# Plot for SSC
for (letter in unique(d_ss$flask)) {
  FLASK<- filter(d_ss,flask == letter)
SSC <- ggplot(FLASK, aes(x = FLASK$julian_time, y = FLASK$`Picochlorum Median SSC-A`))+
    geom_point(aes(color = lightORdark)) +
    xlab("Time since start") +
    ylab("Median SSC") + 
    labs(col="Light \nCondition") +
    theme_bw() +
    ggtitle(paste("Flask", letter)) + 
    theme(plot.title = element_text(size = 28, face = "bold"),
          axis.text=element_text(size=20),
          axis.title=element_text(size=20,face="bold"),
          legend.title =element_text(size=20,face="bold"),
          legend.text = element_text(size=20)) 
    # Create and store plots in img folder
  dev.new()
    png(file.path("../report/img",paste("SSC", letter, ".png", sep="_")), width = 800, height = 600)
  print(SSC)
  dev.off()  
}

# Plot for CHL-A 
for (letter in unique(d_ss$flask)) {
  FLASK<- filter(d_ss,flask == letter)
PC5.5 <- ggplot(FLASK, aes(x = FLASK$julian_time, y = FLASK$`Picochlorum Median PC5.5-A`))+
    geom_point(aes(color = lightORdark)) +
    xlab("Time since start") +
    ylab("Median PC5.5") + 
    labs(col="Light \nCondition") +
    theme_bw() +
    ggtitle(paste("Flask", letter)) + 
    theme(plot.title = element_text(size = 28, face = "bold"),
          axis.text=element_text(size=20),
          axis.title=element_text(size=20,face="bold"),
          legend.title =element_text(size=20,face="bold"),
          legend.text = element_text(size=20)) 
    # Create and store plots in img folder
  dev.new()
    png(file.path("../report/img",paste("PC5.5", letter, ".png", sep="_")), width = 800, height = 600)
  print(PC5.5)
  dev.off()    
}
  
# This is to clear the device list (dev.list()) 
graphics.off()



## Find out how to normalise this! Use the other columns in your analysis
# Plot of multiple light regimes together 
REGIME<-filter(d_ss,light_regime == "1608")
regime_plot <- ggplot(REGIME, aes(x = REGIME$julian_time, y = REGIME$`Picochlorum Events/μL(V)`))+
  geom_point(aes(color = lightORdark, shape = flask)) +
  xlab("Time Since Start") +
  ylab("FSC") + 
  labs(col="Light \nCondition", shape = "Flask") +
  theme_bw()+ 
  theme(axis.text=element_text(size=28),
        axis.title=element_text(size=28,face="bold"),
        legend.title =element_text(size=28,face="bold"),
        legend.text = element_text(size=28))
regime_plot



```



```{r}
# Comparing A and M samples

# group_by selects all the descriptive columns so that the function later on applied through summarise_at will not affect it. 
d_ss_mean <- d_ss %>% 
  group_by(flask, attempt,hour_index, FAhi, AorM,light_regime, julian_time,sample_datetime, sample_time, lightORdark, time_since_tube_change) %>% 
  summarise_at(.vars = names(.)[13:16],
               .funs = c(mean="mean"))

# Keep only rows of FAhi where both A and M exist
d_ss_mean_AM <- subset(d_ss_mean, FAhi %in% d_ss_mean[duplicated(d_ss_mean$FAhi),"FAhi"]$FAhi)

# Compare differences in 
d_ss_mean_AM_A <- filter(d_ss_mean_AM,AorM == "A")
d_ss_mean_AM_M <- filter(d_ss_mean_AM,AorM == "M")
d_ss_mean_AM_A_ratio <-data.frame(c(d_ss_mean_AM_A[1:11],d_ss_mean_AM_A[-c(1:11)]/d_ss_mean_AM_M[-c(1:11)]))

preservation_plot <- ggplot(d_ss_mean_AM_A_ratio, aes(x = time_since_tube_change, y = Picochlorum.Events.μL.V._mean))+
  geom_point(aes(color = flask)) +
  xlab("Time Since Tube Change") +
#  ylab("FSC") + 
  labs(col = "Flask") +
  theme_bw()
preservation_plot


```
```{r}
# Derivatives of events/ul graph to determine instantaneous growth rates!! 
# Trying out npregfast package to get nonparametric derivative estimations 

# # Test flask use E 
# d_ss_mean <- d_ss_mean %>% transform(hour_index = as.numeric(hour_index))
# 
# FLASK <- filter(d_ss_mean, flask == "E")
# FLASK2 <- filter(d_ss_mean, flask == "F")
# # Plot of actual plus derivative!!! 
# fit <- frfast(`Picochlorum.Events.μL.V._mean`~ hour_index, data = FLASK)
# fit2 <- frfast(`Picochlorum.Events.μL.V._mean`~ hour_index, data = FLASK2)
# autoplot(fit) + theme_bw()
# autoplot(fit, der = 1) + theme_bw()
# autoplot(fit2, der = 1) + theme_bw()
# 
# 
# # For plotting two derivatives in the same graphic window
#   ders <- lapply(0:2, function(x) autoplot(fit, der = x,col = "red", pcol = "black", lwd = 0.5)+
#                    theme_bw()+
#                    scale_x_continuous(breaks=seq(0,30,1)))
# gridExtra::grid.arrange(grobs = ders, ncol = 1, nrow = 3)
# 
# what <- data.frame(cbind(der = c("Estimation","First_der", "Second_der"), rbind(critical(fit)[[1]], critical(fit)[[2]], critical(fit)[[3]])))

# Now make it into a loop and generate a plot for each 
crit_pts <- data.frame()
for (letter in unique(d_ss_mean$flask)) {
  FLASK<- filter(d_ss_mean,flask == letter)
  fit <- frfast(`Picochlorum Events/μL(V)_mean`~ hour_index, data = FLASK)
  ders <- lapply(0:2, function(x) autoplot(fit, der = x,col = "red", pcol = "black", lwd = 0.5)+
                   theme_bw()+
                   ggtitle(paste("Flask", letter)) +
                   scale_x_continuous(breaks=seq(0,28,1)))
  # Create and store plots in img folder
  dev.new()
    png(file.path("../report/img",paste("model_EVENTS_der", letter, ".png", sep="_")), width = 800, height = 800)
  gridExtra::grid.arrange(grobs = ders, ncol = 1, nrow = 3)
  dev.off()    
  # Creation of dataframe containing critical point info
  crit_pts <- rbind(crit_pts,data.frame(cbind(flask = c(letter,letter,letter),der = c("Estimation","First_der", "Second_der"), rbind(critical(fit)[[1]], critical(fit)[[2]], critical(fit)[[3]]))))
}

# While critical does a good job in identifying the hour_index at the point of inflection for some of the plots, very often it is looking at the wrong maximum of the covariate of x for the estimate, or the wrong maximum for the 1st der, or the  wrong intersection with 0 for the 2nd der. In the cases that it is totally off, we will just get the results manually through looking at the graph: 

events_change <- data.frame(flask = c("E","F","G","J","K","L" ),
                     hour_index = c(12.5645645645646, 
                                12.8, 
                                13.2,
                                13.7,
                                14,
                                13.2632632632633),
                     light_regime = c("1608","1608","1212","0816","0816","1212")) 

dev.new()
  png(file.path("../report/img",paste("Max_Events", "Change", ".png", sep="_")), width = 1200, height = 600)
  ggplot(events_change, aes(light_regime, hour_index))+
    geom_point(aes(color = light_regime, size = 2)) + 
    coord_flip() +
    geom_text(aes(label= flask),hjust=1.5, vjust=-1) + 
    scale_y_continuous(limits = c(12,14.5)) +
    theme_bw() +
    ggtitle("Events change") + 
    theme(axis.text=element_text(size=16),
        axis.title=element_text(size=16,face="bold"),
        legend.title =element_text(size=16,face="bold"),
        legend.text = element_text(size=16))
dev.off()  

#### Try to repeat procedure using FSC to see if there are big differences in growth rate changes? FSC should b inversely proportional to growth rates? when they divide, FSC should ~ half 

for (letter in unique(d_ss_mean$flask)) {
  FLASK<- filter(d_ss_mean,flask == letter)
  fit <- frfast(`Picochlorum Median FSC-A_mean`~ hour_index, data = FLASK)
  ders <- lapply(0:2, function(x) autoplot(fit, der = x,col = "red", pcol = "black", lwd = 0.5)+
                   theme_bw()+
                   scale_x_continuous(breaks=seq(0,28,1)))
  # Create and store plots in img folder
  dev.new()
    png(file.path("../report/img",paste("model_FSC_der", letter, ".png", sep="_")), width = 800, height = 800)
  gridExtra::grid.arrange(grobs = ders, ncol = 1, nrow = 3)
  dev.off()    
}

FSC_change <- data.frame(flask = c("E","F","G","J","K","L" ),
                     hour_index = c(11.8, 
                                12.6, 
                                12.7,
                                11.8,
                                12.4,
                                12.6),
                     light_regime = c("1608","1608","1212","0816","0816","1212")) 

dev.new()
  png(file.path("../report/img",paste("Max_FSC", "Change", ".png", sep="_")), width = 1200, height = 600)
  ggplot(FSC_change, aes(light_regime, hour_index))+
    geom_point(aes(color = light_regime, size = 2)) + 
    coord_flip() +
    geom_text(aes(label= flask),hjust=1.5, vjust=-1) + 
    scale_y_continuous(limits = c(11,13.5)) +
    theme_bw() +
    ggtitle("FSC change") + 
    theme(axis.text=element_text(size=16),
        axis.title=element_text(size=16,face="bold"),
        legend.title =element_text(size=16,face="bold"),
        legend.text = element_text(size=16))
dev.off()  


#### SSC!!!!!

for (letter in unique(d_ss_mean$flask)) {
  FLASK<- filter(d_ss_mean,flask == letter)
  fit <- frfast(`Picochlorum Median SSC-A_mean`~ hour_index, data = FLASK)
  ders <- lapply(0:2, function(x) autoplot(fit, der = x,col = "red", pcol = "black", lwd = 0.5)+
                   theme_bw()+
                   scale_x_continuous(breaks=seq(0,28,1)))
  # Create and store plots in img folder
  dev.new()
    png(file.path("../report/img",paste("model_SSC_der", letter, ".png", sep="_")), width = 800, height = 800)
  gridExtra::grid.arrange(grobs = ders, ncol = 1, nrow = 3)
  dev.off()    
}

SSC_change <- data.frame(flask = c("E","F","G","J","K","L" ),
                     hour_index = c(11.8, 
                                12.7, 
                                12.8,
                                12,
                                12.45,
                                13.2),
                     light_regime = c("1608","1608","1212","0816","0816","1212")) 

dev.new()
  png(file.path("../report/img",paste("Max_SSC", "Change", ".png", sep="_")), width = 1200, height = 600)
  ggplot(SSC_change, aes(light_regime, hour_index))+
    geom_point(aes(color = light_regime, size = 2)) + 
    coord_flip() +
    geom_text(aes(label= flask),hjust=1.5, vjust=-1) + 
    scale_y_continuous(limits = c(11,13.5)) +
    theme_bw() +
    ggtitle("SSC change") + 
    theme(axis.text=element_text(size=16),
        axis.title=element_text(size=16,face="bold"),
        legend.title =element_text(size=16,face="bold"),
        legend.text = element_text(size=16))
dev.off()  

#### PC5.5!!!

for (letter in unique(d_ss_mean$flask)) {
  FLASK<- filter(d_ss_mean,flask == letter)
  fit <- frfast(`Picochlorum Median PC5.5-A_mean`~ hour_index, data = FLASK)
  ders <- lapply(0:2, function(x) autoplot(fit, der = x,col = "red", pcol = "black", lwd = 0.5)+
                   theme_bw()+
                   scale_x_continuous(breaks=seq(0,28,1)))
  # Create and store plots in img folder
  dev.new()
    png(file.path("../report/img",paste("model_PC5.5_der", letter, ".png", sep="_")), width = 800, height = 800)
  gridExtra::grid.arrange(grobs = ders, ncol = 1, nrow = 3)
  dev.off()    
}

PC5.5_change <- data.frame(flask = c("E","F","G","J","K","L" ),
                     hour_index = c(11.8, 
                                12.6, 
                                12.5,
                                10.5,
                                12.2,
                                11.6),
                     light_regime = c("1608","1608","1212","0816","0816","1212")) 

dev.new()
  png(file.path("../report/img",paste("Max_PC5.5", "Change", ".png", sep="_")), width = 1200, height = 600)
  ggplot(PC5.5_change, aes(light_regime, hour_index))+
    geom_point(aes(color = light_regime, size = 2)) + 
    coord_flip() +
    geom_text(aes(label= flask),hjust=1.5, vjust=-1) + 
    scale_y_continuous(limits = c(9.5,13.5)) +
    theme_bw() +
    ggtitle("PC5.5 change") + 
    theme(axis.text=element_text(size=16),
        axis.title=element_text(size=16,face="bold"),
        legend.title =element_text(size=16,face="bold"),
        legend.text = element_text(size=16))
dev.off()  

# This is to clear the device list (dev.list()) 
graphics.off()

```






Everything below here is irrelevant 
```{r}

#### EXAMPLE DATASET #####
data(barnacle)
# Nonparametric regression without interactions
fit <- frfast(DW ~ RC, data = barnacle, nboot = 50)
autoplot(fit)
autoplot(fit, points = FALSE) + ggtitle("Title")
autoplot(fit, der = 1) + xlim(4, 20)
autoplot(fit, der = 1, col = "red", CIcol = "blue")
# Nonparametric regression with interactions
fit2 <- frfast(DW ~ RC : F, data = barnacle, nboot = 50)
autoplot(fit2, fac = "barca")
autoplot(fit2, der = 1, fac = "lens")
# Visualization of the differences between two factor's levels
autoplot(fit2, fac = "barca", diffwith = "lens")
autoplot(fit2, der = 1, fac = "barca", diffwith = "lens")
#Plotting in the same graphics device
## Not run:
if (requireNamespace("gridExtra", quietly = TRUE)) {
# For plotting two derivatives in the same graphic windows
ders <- lapply(0:1, function(x) autoplot(fit, der = x))
gridExtra::grid.arrange(grobs = ders, ncol = 2, nrow = 1)
# For plotting two levels in the same graphic windows
facs <- lapply(c("barca", "lens"), function(x) autoplot(fit2, der = 0, fac = x))
gridExtra::grid.arrange(grobs = facs, ncol = 2, nrow = 1)
}
## End(Not run)


# Example of prediction
# Nonparametric regression without interactions
fit <- frfast(DW ~ RC, data = barnacle, nboot = 100)
nd <- data.frame(RC = c(10, 14, 18))
predict(fit, newdata = nd)


# Example of finding critical points in the 1st and 2nd derivative curves 
fit <- frfast(DW ~ RC, data = barnacle) # without interactions
critical(fit)
critical(fit, der = 0)
critical(fit, der = 1)
critical(fit, der = 2)


```





```{r}

## UPDATE: THIS PORTION IS NO LONGER APPLICABLE BECAUSE npregfast > pspline
# This is because 1. npregfast can hv >1 value at each x axis point in generating a smooth curve, 2. npregfast uses ggplot graphics, 3. npregfast has a smoother curve and the derivative estimate looks visually better than pspline. 4. npregfast has autoplot functions :') 


# Try to get a model for instantaneous growth rates!! 
# Trying out pspline package to get nonparametric derivative estimations 

# Since pspline requires dataset to not have more than 1 value for each point on the x axis, have to find the d_ss_mean, but with all the A and M values meaned out as well. 
d_ss_mean_noAM <- d_ss %>% 
  group_by(flask, attempt,hour_index, FAhi,light_regime, julian_time,sample_datetime, sample_time, lightORdark) %>% 
  summarise_at(.vars = names(.)[13:16],
               .funs = c(mean="mean"))

# Test flask use E 
FLASK <- filter(d_ss_mean_noAM, flask == "E")

# create estimate of curve using smooth.Pspline() function 
pspl <- smooth.Pspline(FLASK$julian_time, FLASK$`Picochlorum Events/μL(V)_mean`,norder =3 )
d0 <- predict(pspl, FLASK$julian_time, nderiv=0)
plot(pspl)
lines(FLASK$julian_time, d0, lwd=3, lty=2, col="red")


d1 <- predict(pspl, FLASK$julian_time, nderiv=1)
plot(FLASK$julian_time, d1)
lines(FLASK$julian_time, d1, lwd=3, lty=2, col="red")
gr_data <- data.frame("x" = FLASK$julian_time, "y" =FLASK$`Picochlorum Events/μL(V)_mean`, "d0" = d0, "d1" = d1)

p <- ggplot(data =gr_data) + 
  geom_point(aes(x = x, y = y)) + 
  geom_smooth(aes(x = x, y = y))

  geom_point(aes(x=x, y= d1))

print(p)


## UPDATE: This portion is no longer applicable because linear models are trash D: 
# Linear Model of Ln Events/ul to get growth rates etc 

# Create function to generate regression plot 
ggplotRegression <- function (fit) {
require(ggplot2)
ggplot(fit$model, aes(x = fit$model[,2], y = fit$model[,1])) + 
  geom_point() +
  stat_smooth(method = "lm", col = "red") +
  xlab(names(model$model[2]))+ 
  ylab(names(model$model[1])) +
  labs(title = paste("Adj R2 = ",signif(summary(fit)$adj.r.squared, 5),
                     "Intercept =",signif(fit$coef[[1]],5 ),
                     " Slope =",signif(fit$coef[[2]], 5),
                     " P =",signif(summary(fit)$coef[2,4], 5))) +
  theme_bw()
}

# Create function to capture and calculate growth rate data
growth_rate <- function (model){
  # Use fitted.values so that you are taking the slope of the linear model and not calculating growth rates based on 1st and last points alone! 
  (last(model$fitted.values)-first(model$fitted.values))/as.numeric(last(model$model[2][,1])-first(model$model[2][,1]))
}

# Plot and store growth rate data
growth_data <- data.frame()
plot_list = list()

for (letter in 1:as.numeric(tally(plyr::count(unique(d_ss_mean$flask))))) {
  FLASK <- filter(d_ss_mean, flask == unique(d_ss_mean$flask)[letter])
  # Plot model for each flask
  model = lm(log(FLASK$`Picochlorum Events/μL(V)_mean`)~ sample_datetime, data = FLASK)
  # Create File path and name for each plot generated
  file_name <- file.path("../report/img",paste("linear_model_flask_", unique(d_ss_mean$flask)[letter], ".png", sep=""))
  # Store all models in a list
  plot_list[[letter]] = model
  # Create plot and add title 
  p <- ggplotRegression(model) + ggtitle(paste("Flask", unique(d_ss_mean$flask)[letter]))
  # Print and store all ggplotRegression plots 
  dev.new()
  png(file.path("../report/img",paste("linear_model_flask_", unique(d_ss_mean$flask)[letter], ".png", sep="")), width = 800, height = 600)
  print(p)
  dev.off()
  # Store all growth rate data in a df 
  growth <- c("r" = growth_rate(model), "k" = growth_rate(model)/log(2), "T2" = log(2)/growth_rate(model))
  growth_data <- rbind(growth_data, growth)
}
colnames(growth_data) <- c("r", "k", "T2")
row.names(growth_data) <- unique(d_ss_mean$flask)

# This is to clear the device list (dev.list()) 
graphics.off()


## Plot instantaneous growth rate against time and then find area under the curve to get average growth rate over period or average mortality rate over period 

# Using stat_smooth to get modeled curve 


FLASK<- filter(d_ss,flask == "E")

events <- ggplot(FLASK, aes(x = FLASK$sample_datetime, y = FLASK$`Picochlorum Events/μL(V)`))+
  geom_point(aes(color = lightORdark)) +
  stat_smooth() + 
  xlab("Time since start") +
  ylab("Median Events/μL") + 
  labs(col="Light \nCondition") +
  theme_bw() +
  ggtitle(paste("Flask", "E")) + 
  theme(plot.title = element_text(size = 28, face = "bold"),
        axis.text=element_text(size=20),
        axis.title=element_text(size=20,face="bold"),
        legend.title =element_text(size=20,face="bold"),
        legend.text = element_text(size=20)) 

print(events)
sup <- ggplot_build(events)
sup$data[[2]]
  

  
# Gets a little confusing so lets try with ggplot using the splines package
# Also super confusing 

# Another package called npregfast seems possible but is too complicated for me :(


# Try to use lm to fit a model from sin and cos curves 
  # The datetime format is a problem
evnts <- FLASK$`Picochlorum Events/μL(V)`
timee <- FLASK$sample_datetime

model_test <- lm(evnts~sin(as.numeric(timee)))
summary(model_test)

model <- loess(evnts~as.numeric(timee))


tcos<-cos(2*pi*(as.numeric(timee))/1234)
tsin<-sin(2*pi*(as.numeric(timee))/1234)
model <-lm(evnts~tcos + tsin)
summary(model)

model1 <- lm(y~ x + I(sin(2*pi*x/360)))
summary(model1)

model2 <- lm(y~ x + I(sin(2*pi*x/360))+I(cos...))
summary(model2)
# Derivative of this curve is formula for instantaneous growth rate for time (t)

# Integral of the new growth rate curve below line and above axis is growing and below axis and above line is dying

```







